import{test,expect}from'@playwright/test';import{boot,adv,state}from'./helpers.mjs';
const errors=new WeakMap();test.beforeEach(async({page})=>{const list=[];errors.set(page,list);page.on('pageerror',e=>list.push(String(e)));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});});test.afterEach(async({page})=>expect(errors.get(page)).toEqual([]));
async function tier(page,value){await page.evaluate(async n=>{const{gameState}=await import('/src/core/GameState.js'),{HEAT}=await import('/src/core/Constants.js');gameState.heat.tier=n;gameState.heat.points=HEAT.TIER_THRESHOLDS[n];gameState.heat.target=n;},value);}

test('five-star infantry arrive gradually, remain bounded when collected, and reset with the run',async({page})=>{
 await boot(page);expect(await page.evaluate(()=>__game.pursuers.response.infantryReady)).toBe(true);await tier(page,4);await adv(page,.1);expect((await state(page)).pursuers.filter(p=>p.type==='infantry')).toHaveLength(0);
 await tier(page,5);await adv(page,.1);let s=await state(page);expect(s.pursuers.filter(p=>p.type==='infantry')).toHaveLength(1);
 const r=await page.evaluate(async()=>{const g=__game,ai=g.pursuers,{eventBus,Events}=await import('/src/core/EventBus.js');for(let i=0;i<12;i++){for(const p of ai.infantry)eventBus.emit(Events.ENTITY_ATTACH,{id:`pursuer-${p.id}`});ai.update(1);}return{count:ai.infantry.length,attached:ai.infantry.filter(p=>p.attached).length,models:ai.infantry.map(p=>p.model),bodies:ai.infantry.map(p=>g.physics.actors.has(`pursuer-${p.id}`))};});expect(r.count).toBe(4);expect(r.attached).toBe(4);expect(r.models).toEqual(Array(4).fill('infantry'));expect(r.bodies.every(Boolean)).toBe(true);
 await page.evaluate(()=>restartGame());await adv(page,.1);s=await state(page);expect(s.pursuers.filter(p=>p.type==='infantry')).toHaveLength(0);expect(s.response.bullets).toBe(0);expect(s.response.rifleShots).toBe(0);
});

async function soldier(page){
 page.on('console',m=>{if(m.text().startsWith('INFANTRY_BOOT'))console.log(m.text());});
 await page.addInitScript(()=>{const t=setInterval(()=>{const g=window.__game,r={rig:g?.jimothy.rig.loaded,pedestrians:g?.pedestrians.ready,trash:g?.trashCans.ready,interiors:g?.interiors.ready,street:g?.streetLife.ready,environment:g?.environmentLife.ready,infantry:g?.pursuers.response.infantryReady};console.log('INFANTRY_BOOT',JSON.stringify(r));if(Object.values(r).every(Boolean))clearInterval(t);},10000);});
 await boot(page,{withRig:true});expect(await page.evaluate(()=>__game.pursuers.response.infantryReady)).toBe(true);await tier(page,5);
 await page.evaluate(async()=>{const g=__game,ai=g.pursuers,{gameState}=await import('/src/core/GameState.js');ai.reset();g.police.reset();teleportJimothy(-6,-6);const j=g.jimothy.position,id=spawnPursuerAt('infantry',j.x,j.z-7),p=ai.all.find(p=>p.id===id);p.group.position.y=ai._groundY(p.group.position.x,p.group.position.z);p.group.rotation.y=0;p.sees=true;p.state='chase';p.grounding.reset();gameState.capture.phase='idle';g.jimothy.hitCooldown=0;window.soldier=p;
  window.rifleTick=(dt=1/60)=>{p.sees=true;ai._animate(p,dt,p.group.position.x,p.group.position.z);p.responsePose.apply(dt,p.fire.target||g.jimothy.body.position);ai.response.gun(p,dt);ai.response.update(dt);};
 });
}

test('a distinct MPFB soldier holds a long rifle in both hands and warns before a three-round burst',async({page})=>{
 await soldier(page);const r=await page.evaluate(async()=>{const g=__game,p=soldier,ai=g.pursuers,{INFANTRY:C}=await import('/src/core/Constants.js');let warning=null,peak=0;for(let i=0;i<180;i++){rifleTick();peak=Math.max(peak,ai.response.bullets.length);if(p.fire.phase==='aim'&&!warning){const hand=p.visual.getObjectByName('hand_l').getWorldPosition(g.jimothy.position.clone());warning={shots:ai.response.rifleShots,gap:hand.distanceTo(p.gun.localToWorld(hand.clone().fromArray(C.GUN_LEFT))),model:p.model,held:p.gun.parent.name,helmet:p.cap?.name};}}g.scene.updateMatrixWorld(true);const THREE=await import('/node_modules/three/build/three.module.js'),headBox=new THREE.Box3();p.visual.traverse(o=>{if(o.isSkinnedMesh){o.skeleton.update();o.computeBoundingBox();headBox.union(o.boundingBox.clone().applyMatrix4(o.matrixWorld));}});const helmet=new THREE.Box3().setFromObject(p.cap);return{warning,helmet:{bottom:helmet.min.y-headBox.max.y,top:helmet.max.y-headBox.max.y},shots:ai.response.rifleShots,peak,phase:p.fire.phase,playing:JSON.parse(render_game_to_text()).game.isPlaying};});
 expect(r.warning).toMatchObject({shots:0,model:'infantry',held:'hand_r',helmet:'infantry-helmet'});console.log('INFANTRY_FIT',JSON.stringify(r));expect(r.helmet.bottom).toBeLessThan(-.035);expect(r.helmet.top).toBeGreaterThan(-.03);expect(r.helmet.top).toBeLessThan(.08);expect(r.warning.gap).toBeLessThan(.1);expect(r.shots).toBe(3);expect(r.peak).toBeLessThanOrEqual(12);expect(r.phase).toBe('recover');expect(r.playing).toBe(true);
});

test('a sideways dodge avoids the committed rifle burst; interrupting ownership cancels the remaining rounds',async({page})=>{
 await soldier(page);const r=await page.evaluate(async()=>{const g=__game,ai=g.pursuers,p=soldier,{gameState}=await import('/src/core/GameState.js'),{eventBus,Events}=await import('/src/core/EventBus.js');for(let i=0;i<120&&p.fire.phase!=='aim';i++)rifleTick();if(p.fire.phase!=='aim')throw Error('No warning');const locked={...p.fire.target};g.jimothy.body.position.x+=4;for(let i=0;i<160;i++)rifleTick();const dodge={shots:ai.response.rifleShots,hits:ai.response.gunHits};g.jimothy.body.position.x-=4;
  const starts=[],ends=[];const start=()=>{p.fire.phase='idle';p.fire.time=0;p.fire.target=null;p.responsePose.raised=1;p.sees=true;ai.response.gun(p,.1);starts.push(p.fire.phase);};
  start();gameState.capture.phase='windup';ai.response.gun(p,.1);ends.push(p.fire.phase);gameState.capture.phase='idle';
  start();gameState.tools.shield=1;ai.response.gun(p,.1);ends.push(p.fire.phase);gameState.tools.shield=0;
  start();gameState.vehicle.phase='driving';ai.response.gun(p,.1);ends.push(p.fire.phase);gameState.vehicle.phase='onFoot';
  start();p.sees=false;ai.response.gun(p,.1);ends.push(p.fire.phase);
  start();eventBus.emit(Events.HUMAN_DOWN,{id:`pursuer-${p.id}`,active:true});ends.push(p.fire.phase);p.ragdoll=false;
  start();eventBus.emit(Events.ENTITY_ATTACH,{id:`pursuer-${p.id}`});ends.push(p.fire.phase);
  return{locked,dodge,starts,ends};});expect(r.dodge).toEqual({shots:3,hits:0});expect(r.starts).toEqual(Array(6).fill('aim'));expect(r.ends).toEqual(Array(6).fill('recover'));
});

test('a real wall catches rifle rounds; hostile hits use mass-sensitive recovery without wanted credit',async({page})=>{
 await soldier(page);const r=await page.evaluate(async()=>{const g=__game,ai=g.pursuers,p=soldier,{VOXEL}=await import('/src/core/Constants.js'),{gameState}=await import('/src/core/GameState.js'),{eventBus,Events}=await import('/src/core/EventBus.js');for(let i=0;i<150&&!ai.response.bullets.length;i++)rifleTick();if(!ai.response.bullets.length)throw Error('No rifle projectile');const b=ai.response.bullets[0],mid=b.mesh.position.clone().lerp(g.jimothy.body.position,.5),s=VOXEL.SIZE,edits=[];
  for(let x=Math.floor((mid.x-.8)/s);x<=Math.ceil((mid.x+.8)/s);x++)for(let y=Math.floor((mid.y-.8)/s);y<=Math.ceil((mid.y+.8)/s);y++){const z=Math.floor(mid.z/s);edits.push([x,y,z,g.voxels.get(x,y,z)]);g.voxels.setEdit(x,y,z,6);}
  let peak=0;for(let i=0;i<30;i++){rifleTick();peak=Math.max(peak,ai.response.particles.length);}const cover={hits:ai.response.gunHits,blocks:ai.response.gunBlocks,peak};for(const[x,y,z,m]of edits)g.voxels.setEdit(x,y,z,m);ai.response.reset();p.fire.phase='idle';p.fire.time=0;const heat=gameState.heat.points;for(let i=0;i<180&&!ai.response.gunHits;i++)rifleTick();const hit={hits:ai.response.gunHits,physical:g.jimothy.ragdoll.physical,bodies:g.jimothy.ragdoll.snapshot().bodies,heatBefore:heat,heatAfter:gameState.heat.points};ai.update=()=>{};advanceTime(5);const recovered={type:g.jimothy.body.type,phase:g.jimothy.ragdoll.phase};setFatness(250);g.jimothy.move={kind:'roll',elapsed:0};g.jimothy.hitCooldown=0;eventBus.emit(Events.PLAYER_HIT,{source:'infantry',velocity:[0,4,9]});return{cover,hit,recovered,giant:{move:g.jimothy.move?.kind,physical:g.jimothy.ragdoll.physical}};});
 expect(r.cover.hits).toBe(0);expect(r.cover.blocks).toBeGreaterThan(0);expect(r.cover.peak).toBeGreaterThan(0);expect(r.hit.hits).toBe(1);expect(r.hit.physical).toBe(true);expect(r.hit.bodies).toBe(11);expect(r.hit.heatAfter).toBe(r.hit.heatBefore);expect(r.recovered.type).toBe(4);expect(r.giant).toEqual({move:'roll',physical:false});
});

test('infantry search observed positions, retire at distance and leave no effects after restart',async({page})=>{
 await soldier(page);const r=await page.evaluate(async()=>{const g=__game,ai=g.pursuers,p=soldier;p.manual=false;p.lastKnown={x:12,z:6};p.state='search';p.searchTimer=12;p.target={...p.lastKnown};p.sees=false;g.voxels.hasLineOfSight=()=>false;teleportJimothy(25,30);for(let i=0;i<60;i++)ai._think(p,1/60);const memory={...p.lastKnown},radar=ai.radarContacts().find(q=>q.id===`pursuer-${p.id}`);teleportJimothy(200,200);ai.update(0);return{memory,radar:radar?.kind,oldGone:!ai.all.includes(p),actorGone:!g.physics.actors.has(`pursuer-${p.id}`)};});expect(r.memory).toEqual({x:12,z:6});expect(r.radar).toBe('infantry');expect(r.oldGone).toBe(true);expect(r.actorGone).toBe(true);
 await page.evaluate(()=>restartGame());await adv(page,.1);const s=await state(page);expect(s.response.bullets).toBe(0);expect(s.response.particles).toBe(0);expect(s.response.rifleShots).toBe(0);
});

test('repeated rifle bursts keep effects and audio bounded, and five-star capture still works',async({page})=>{
 await soldier(page);await page.keyboard.press('h');await page.waitForFunction(()=>__game.pursuers.response.audio?.currentTime>.1);await page.evaluate(()=>__game.pursuers.response.cue('rifle',__game.jimothy.position));await expect.poll(async()=>(await state(page)).response.rms,{timeout:1500,intervals:[20]}).toBeGreaterThan(.00001);
 const r=await page.evaluate(()=>{const a=__game.pursuers.response;let bullets=0,particles=0,voices=0;for(let i=0;i<1800;i++){rifleTick();bullets=Math.max(bullets,a.bullets.length);particles=Math.max(particles,a.particles.length);voices=Math.max(voices,a.voices.size);}return{shots:a.rifleShots,bullets,particles,voices};});expect(r.shots).toBeGreaterThan(12);expect(r.bullets).toBeLessThanOrEqual(12);expect(r.particles).toBeLessThanOrEqual(40);expect(r.voices).toBeLessThanOrEqual(4);
 await page.evaluate(()=>restartGame());await adv(page,.1);await tier(page,5);let s=await state(page);for(let i=0;i<40&&!s.game.netted;i++){await adv(page,1);s=await state(page);}expect(s.game.netted).toBe(true);expect(s.game.isPlaying).toBe(false);
});

test('a blasted soldier uses shared articulated physics, stops firing and can be collected without duplicate bodies',async({page})=>{
 await soldier(page);const r=await page.evaluate(async()=>{const g=__game,p=soldier,ai=g.pursuers,id=`pursuer-${p.id}`,{eventBus,Events}=await import('/src/core/EventBus.js');for(let i=0;i<100&&p.fire.phase!=='aim';i++)rifleTick();eventBus.emit(Events.HUMAN_IMPACT,{id,x:p.group.position.x-1,z:p.group.position.z,radius:2,power:1});const rag=g.physics.ragdolls.get(id),start={physical:p.ragdoll,bodies:rag?.bodies.length,joints:rag?.constraints.length,phase:p.fire.phase};const shots=ai.response.rifleShots;for(let i=0;i<30;i++){g.physics.update(1/60);g.ragdolls.update(1/60);ai.update(1/60);}const moved=rag?.bodies[0].velocity.length();eventBus.emit(Events.ENTITY_ATTACH,{id});const held={attached:p.attached,ragdoll:g.physics.ragdolls.has(id),active:g.ragdolls.active.has(id),actor:g.physics.actors.get(id).active};return{start,held,moved,shots,after:ai.response.rifleShots};});
 expect(r.start).toEqual({physical:true,bodies:11,joints:10,phase:'recover'});expect(r.moved).toBeGreaterThan(.1);expect(r.after).toBe(r.shots);expect(r.held).toEqual({attached:true,ragdoll:false,active:false,actor:false});
});

test('infantry dispatch finds clear grounded land and declines open water',async({page})=>{
 await boot(page);await page.waitForFunction(()=>__game.pursuers.response.infantryReady);const rows=await page.evaluate(async()=>{const g=__game,ai=g.pursuers,{eventBus,Events}=await import('/src/core/EventBus.js'),rows=[];for(const [x,z]of [[0,0],[67,70],[-70,90],[-850,0]]){teleportJimothy(x,z);g.voxels.processGeneration();const at=ai._infantrySpawn();if(!at){rows.push({x,z,spawn:false});continue;}const y=ai._groundY(...at);let water;eventBus.emit(Events.WATER_SAMPLE,{x:at[0],z:at[1],receive:w=>water=w});rows.push({x,z,spawn:true,buried:g.voxels.physicalSolidAtWorld(at[0],y+1,at[1]),submerged:!!water&&water.height>y+.4,finite:Number.isFinite(y)});}return rows;});console.log('INFANTRY_SPAWN',JSON.stringify(rows));expect(rows[0].spawn).toBe(true);expect(rows.at(-1).spawn).toBe(false);for(const r of rows.filter(r=>r.spawn)){expect(r.buried).toBe(false);expect(r.submerged).toBe(false);expect(r.finite).toBe(true);}
});
