import {test,expect} from '@playwright/test';import {boot,adv} from './helpers.mjs';
test('soil chunks and visible rubble have bodies; expired pools and restart leave no ghosts',async({page})=>{
 await boot(page);const initial=await page.evaluate(()=>{const g=__game;return {pool:g.debris.slots.filter(s=>s.body.world).length};});expect(initial.pool).toBe(0);
 const out=await page.evaluate(()=>{const g=__game,p=g.jimothy.position;g.military.update=()=>{};g.voxels.queueGroundChannel({...p},{...p},5,2);advanceTime(.4);return {clods:g.groundChannels.clods.map(c=>g.physics.props.get(c.id)?.active),pool:g.debris.slots.filter(s=>s.body.world).length};});expect(out.clods.length).toBeGreaterThan(0);expect(out.clods.every(Boolean)).toBe(true);
 await adv(page,8);expect(await page.evaluate(()=>__game.debris.slots.filter(s=>s.body.world).length)).toBe(0);
 await page.evaluate(()=>restartGame());expect(await page.evaluate(()=>({clods:[...__game.physics.props.keys()].filter(id=>id.startsWith('soil-clod:')).length,fragments:__game.structuralSupport.fragments.length,detached:[...__game.physics.actors.values()].filter(a=>a.active&&!a.mesh.parent).length}))).toEqual({clods:0,fragments:0,detached:0});
});
test('Jimothy lands on a physical slab and loses support when it is removed',async({page})=>{
 await boot(page);const r=await page.evaluate(async()=>{const g=__game,THREE=await import('/node_modules/three/build/three.module.js'),{eventBus,Events}=await import('/src/core/EventBus.js');g.military.update=()=>{};teleportJimothy(-2,-40);advanceTime(.2);g.streetLife.update=()=>{};for(const [id,p]of g.physics.props)if(p.mesh.position.distanceTo(g.jimothy.position)<6)eventBus.emit(Events.PROP_SUSPEND,{id});for(const c of g.trashCans.cans)if(c.body.position.distanceTo(g.jimothy.body.position)<6)g.physics.remove(c.body);const j=g.jimothy,ground=j.body.position.y-j.radius,mesh=new THREE.Object3D();mesh.position.set(-2,ground+.2,-40);eventBus.emit(Events.PROP_CREATE,{id:'test-slab',mesh,half:[.8,.2,.8],mass:800,loose:true});j.body.position.y+=1;j.body.velocity.setZero();advanceTime(1.5);return {above:j.body.position.y-j.radius-ground,grounded:j.grounded};});expect(r.above).toBeGreaterThan(.3);expect(r.above).toBeLessThan(.6);
 await page.evaluate(async()=>{const {eventBus,Events}=await import('/src/core/EventBus.js');eventBus.emit(Events.PROP_REMOVE,{id:'test-slab'});});await adv(page,1);expect(await page.evaluate(()=>{const j=__game.jimothy;return j.body.position.y-j.radius-__game.voxels.groundHeightAt(j.body.position.x,j.body.position.z,j.body.position.y,0);})).toBeLessThan(.15);
});
test('a falling heavy chunk knocks down a pedestrian through shared contact',async({page})=>{
 await boot(page);await page.evaluate(async()=>{const g=__game,THREE=await import('/node_modules/three/build/three.module.js'),{eventBus,Events}=await import('/src/core/EventBus.js');g.military.update=()=>{};const p=g.pedestrians.people[0];window.__rubblePed=p;window.__rubbleDown=false;eventBus.on(Events.HUMAN_DOWN,e=>{if(e.id===p.id&&e.active)__rubbleDown=true;});g.pedestrians.update=()=>{};const mesh=new THREE.Object3D();mesh.position.copy(p.mesh.position).add(new THREE.Vector3(0,3,0));eventBus.emit(Events.PROP_CREATE,{id:'falling-wall',kind:'building',mesh,half:[.5,.35,.5],mass:120,loose:true});});await adv(page,1);expect(await page.evaluate(()=>__rubbleDown)).toBe(true);
});
test('ocean fish and seabed crabs participate in nearby rubble contact and clean up',async({page})=>{
 await boot(page);await page.waitForFunction(()=>__game.ocean.ready);await page.evaluate(()=>{const s=__game.ocean.sites.find(s=>s.kind==='wreck');teleportJimothy(s.x,s.z);__game.military.update=()=>{};});await adv(page,3);
 const out=await page.evaluate(()=>({fish:__game.ocean.fish.length,proxies:[...__game.physics.actors.values()].filter(a=>a.id.startsWith('ocean-creature:')).length}));expect(out.fish).toBeGreaterThan(0);expect(out.proxies).toBeGreaterThan(out.fish);
 await page.evaluate(()=>restartGame());expect(await page.evaluate(()=>[...__game.physics.actors.keys()].filter(id=>id.startsWith('ocean-creature:')).length)).toBe(0);
});
