import {test,expect} from '@playwright/test';import {boot,adv,state} from './helpers.mjs';
async function setup(page){await boot(page);expect((await state(page)).tools?.catalog?.length||0).toBeGreaterThanOrEqual(8);await page.waitForFunction(()=>__game.tools.ready);await page.evaluate(async()=>{window.__toolState=(await import('/src/core/GameState.js')).gameState;});await page.evaluate(()=>{__game.military.update=()=>{};__toolState.tools.energy=100;});}
test('washer moves a physical target and a solid wall blocks its jet',async({page})=>{
 await setup(page);const r=await page.evaluate(async()=>{const g=__game,t=g.tools,p=t.pickups[0];t.equip(p);const target=t.pickups.find(p=>p.type==='bubble-gun');teleportJimothy(target.mesh.position.x,target.mesh.position.z-3);faceJimothy(0);advanceTime(.1);t.aimOverride={x:0,y:0,z:1};const body=g.physics.props.get(target.id).body;const y=g.jimothy.body.position.y;target.mesh.position.set(g.jimothy.position.x,y,g.jimothy.position.z+3);const {eventBus,Events}=await import('/src/core/EventBus.js');eventBus.emit(Events.PROP_POSE,{id:target.id,position:target.mesh.position,quaternion:target.mesh.quaternion});t.use(.1);const pushed=body.velocity.length();body.velocity.setZero();const v=await import('/src/core/Constants.js');const sz=v.VOXEL.SIZE;for(let iy=-5;iy<6;iy++)for(let ix=-5;ix<6;ix++)g.voxels.set(Math.floor(g.jimothy.position.x/sz)+ix,Math.floor(y/sz)+iy,Math.floor((g.jimothy.position.z+1.5)/sz),1);t.cooldown=0;t.use(.1);return {pushed,blocked:body.velocity.length()};});expect(r.pushed).toBeGreaterThan(0);expect(r.blocked).toBe(0);
});
test('bubbles lift a real person and release them alive without leaving capture or collection ownership',async({page})=>{
 await setup(page);await page.evaluate(()=>{const g=__game,t=g.tools;t.equip(t.pickups.find(p=>p.type==='bubble-gun'));const p=g.pedestrians.people[0];window.__bubbled=p;teleportJimothy(p.x,p.z-4);faceJimothy(0);advanceTime(.1);t.aimOverride={x:0,y:0,z:1};t.use(.1);});await adv(page,1);
 const held=await page.evaluate(()=>({held:__bubbled.attached,y:__bubbled.mesh.position.y,base:__bubbled.y,count:__game.tools.statuses.size}));expect(held.held).toBe(true);expect(held.y).toBeGreaterThan(held.base+.3);expect(held.count).toBeGreaterThan(0);
 await adv(page,5);expect(await page.evaluate(()=>({held:__bubbled.attached,parent:__bubbled.mesh.parent===__game.scene,count:__game.tools.statuses.size}))).toEqual({held:false,parent:true,count:0});
 await page.evaluate(()=>restartGame());expect((await state(page)).tools.statuses).toBe(0);
});
test('suction moves real food while paint and confetti visibly affect reachable targets',async({page})=>{
 await setup(page);const r=await page.evaluate(()=>{const g=__game,t=g.tools;const j=g.jimothy.position;const food=g.trashCans.spawnFood('whole-pizza',j.x,j.z+6);t.equip(t.pickups.find(p=>p.type==='vacuum'));faceJimothy(0);t.aimOverride={x:0,y:0,z:1};const before=food.mesh.position.distanceTo(j);t.use(.2);const after=food.mesh.position.distanceTo(j);t.equip(t.pickups.find(p=>p.type==='paint-sprayer'));t.cooldown=0;const p=g.pedestrians.people[0];teleportJimothy(p.x,p.z-4);faceJimothy(0);advanceTime(.1);t.use(.1);const paint=t.snapshot().paint;t.equip(t.pickups.find(p=>p.type==='confetti-cannon'));t.cooldown=0;t.use(.1);return {before,after,paint,effects:t.snapshot().effects};});expect(r.after).toBeLessThan(r.before);expect(r.paint).toBeGreaterThan(0);expect(r.effects).toBeGreaterThan(0);
});
test('the washer tips a bin so its contents can refill the rampage',async({page})=>{
 await setup(page);await page.evaluate(()=>{const g=__game,t=g.tools,c=g.trashCans.cans.find(c=>!c.tipped);window.__washedCan=c;t.equip(t.pickups.find(p=>p.type==='power-washer'));teleportJimothy(c.body.position.x,c.body.position.z-3);faceJimothy(0);advanceTime(.1);const origin=g.jimothy.body.position;const d=c.mesh.position.clone().sub(origin).normalize();t.aimOverride={x:d.x,y:d.y,z:d.z};});
 await page.keyboard.down('v');await adv(page,1);await page.keyboard.up('v');await adv(page,1);expect(await page.evaluate(()=>__washedCan.tipped)).toBe(true);
});
